site_name: Smart AutoSorter AI Pro API
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_root_heading: true

nav:
  - User Guides: user_guide.md
  - Administrator Guide: admin_guide.md
  - Developer Reference:
    - Core: core.md
    - UI: ui.md
    - Config: config.md
