"""Audit Reporter for post-sort file verification and export operations."""

import csv
import json
import logging
import os
from datetime import datetime, timezone
from typing import Any, Dict, List

from app.core.exceptions import AuditExportError

logger = logging.getLogger(__name__)

VERIFIED_PASS = "VERIFIED_PASS"
MISMATCH_FAIL = "MISMATCH_FAIL"
SKIPPED = "SKIPPED"
UNVERIFIED = "UNVERIFIED"

STATUS_BADGES = {
    VERIFIED_PASS: "[PASS]",
    MISMATCH_FAIL: "[FAIL]",
    SKIPPED: "[SKIPPED]",
    UNVERIFIED: "[UNVERIFIED]",
}


def generate_audit_report(
    base_dir: str, move_records: List[Dict[str, Any]]
) -> Dict[str, Any]:
    """Generate a structured audit report from a collection of move records.

    Args:
        base_dir: Target base directory for the sorting operation.
        move_records: List of dictionaries containing file move information.
            Expected keys per record:
            - source_path (str)
            - destination_path (str)
            - pre_hash (Optional[str])
            - post_hash (Optional[str])
            - status (Optional[str]) - if omitted, computed from pre/post hashes.

    Returns
    -------
        Dict[str, Any]: Complete audit report containing metrics and detailed records.
    """
    base_dir = os.path.normpath(base_dir) if base_dir else ""
    processed_records: List[Dict[str, Any]] = []

    pass_count = 0
    fail_count = 0
    skipped_count = 0
    unverified_count = 0

    for item in move_records:
        src = item.get("source_path") or ""
        dst = item.get("destination_path") or item.get("target_path") or ""
        pre_hash = item.get("pre_hash") or item.get("original_hash")
        post_hash = item.get("post_hash") or item.get("new_hash")
        override_status = item.get("status")

        if override_status in (VERIFIED_PASS, MISMATCH_FAIL, SKIPPED, UNVERIFIED):
            status = override_status
        elif not dst or src == dst or item.get("skipped"):
            status = SKIPPED
        elif pre_hash and post_hash and pre_hash == post_hash:
            status = VERIFIED_PASS
        elif pre_hash and post_hash and pre_hash != post_hash:
            status = MISMATCH_FAIL
        elif post_hash and not pre_hash:
            status = UNVERIFIED
        else:
            status = MISMATCH_FAIL

        if status == VERIFIED_PASS:
            pass_count += 1
        elif status == MISMATCH_FAIL:
            fail_count += 1
        elif status == SKIPPED:
            skipped_count += 1
        elif status == UNVERIFIED:
            unverified_count += 1

        rel_src = (
            os.path.relpath(src, base_dir).replace("\\", "/")
            if src and base_dir
            else src
        )
        rel_dst = (
            os.path.relpath(dst, base_dir).replace("\\", "/")
            if dst and base_dir
            else dst
        )
        filename = os.path.basename(dst or src)

        processed_records.append(
            {
                "filename": filename,
                "relative_source": rel_src,
                "relative_destination": rel_dst,
                "source_path": src,
                "destination_path": dst,
                "pre_hash": pre_hash or "",
                "post_hash": post_hash or "",
                "status": status,
                "status_badge": STATUS_BADGES.get(status, f"[{status}]"),
            }
        )

    total_files = len(processed_records)

    return {
        "base_dir": base_dir,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "total_files": total_files,
        "verified_pass_count": pass_count,
        "mismatch_fail_count": fail_count,
        "skipped_count": skipped_count,
        "unverified_count": unverified_count,
        "records": processed_records,
    }


def export_audit_report_json(report_data: Dict[str, Any], output_path: str) -> str:
    """Export audit report to a structured JSON file on disk.

    Args:
        report_data: Audit report dictionary generated by generate_audit_report.
        output_path: Target output file path.

    Returns
    -------
        str: Absolute path of created JSON file.

    Raises
    ------
        AuditExportError: If file writing or permission checks fail.
    """
    abs_path = os.path.abspath(output_path)
    try:
        os.makedirs(os.path.dirname(abs_path), exist_ok=True)
        with open(abs_path, "w", encoding="utf-8") as f:
            json.dump(report_data, f, indent=2, ensure_ascii=False)
        logger.info(f"Audit report successfully exported to JSON: {abs_path}")
        return abs_path
    except (OSError, IOError, PermissionError) as err:
        msg = f"Failed to export audit report to JSON at {abs_path}: {err}"
        logger.error(msg)
        raise AuditExportError(msg) from err


def export_audit_report_csv(report_data: Dict[str, Any], output_path: str) -> str:
    """Export audit report to a structured CSV file on disk.

    Args:
        report_data: Audit report dictionary generated by generate_audit_report.
        output_path: Target output file path.

    Returns
    -------
        str: Absolute path of created CSV file.

    Raises
    ------
        AuditExportError: If file writing or permission checks fail.
    """
    abs_path = os.path.abspath(output_path)
    try:
        os.makedirs(os.path.dirname(abs_path), exist_ok=True)
        records = report_data.get("records", [])
        fieldnames = [
            "Filename",
            "Status",
            "Status Badge",
            "Pre-Sort SHA-256",
            "Post-Sort SHA-256",
            "Relative Source",
            "Relative Destination",
            "Source Path",
            "Destination Path",
        ]
        with open(abs_path, "w", encoding="utf-8", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(fieldnames)
            for rec in records:
                writer.writerow(
                    [
                        rec.get("filename", ""),
                        rec.get("status", ""),
                        rec.get("status_badge", ""),
                        rec.get("pre_hash", ""),
                        rec.get("post_hash", ""),
                        rec.get("relative_source", ""),
                        rec.get("relative_destination", ""),
                        rec.get("source_path", ""),
                        rec.get("destination_path", ""),
                    ]
                )
        logger.info(f"Audit report successfully exported to CSV: {abs_path}")
        return abs_path
    except (OSError, IOError, PermissionError) as err:
        msg = f"Failed to export audit report to CSV at {abs_path}: {err}"
        logger.error(msg)
        raise AuditExportError(msg) from err


def export_audit_report(
    report_data: Dict[str, Any], output_path: str, format_type: str = "json"
) -> str:
    """Export audit report to disk in specified format ('json' or 'csv').

    Args:
        report_data: Audit report dictionary.
        output_path: Destination file path.
        format_type: Format identifier ('json' or 'csv').

    Returns
    -------
        str: Absolute path of exported report file.
    """
    fmt = format_type.strip().lower()
    if fmt == "csv":
        return export_audit_report_csv(report_data, output_path)
    return export_audit_report_json(report_data, output_path)
